services:
  news:
    build: 
      context: .
      args:
        NEXT_PUBLIC_API_URL: https://api.dinnusmart.com/api
        NEXT_PUBLIC_IMAGE_URL: https://api.dinnusmart.com

    container_name: beyond-media-news

    restart: unless-stopped

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.news.rule=Host(`user.dinnusmart.com`)"

      - "traefik.http.routers.news.entrypoints=websecure"

      - "traefik.http.routers.news.tls.certresolver=letsencrypt"

      - "traefik.http.services.news.loadbalancer.server.port=3000"

    networks:
      - traefik-net

networks:
  traefik-net:
    external: true